version: '3.3'

volumes:
  db_data:

services:
  db:
    container_name: db
    image: 'mariadb:latest'
    volumes:
      - './schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql'
      - 'db_data:/var/lib/mysql'
    env_file:
      - '.env'

  bsuirhub:
    image: 'bsuirhub'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - 'db'